### ISSUE TITLE
How to integrate Django-payments-redsys to Saleor framework

### ISSUE THREAD

**Issue by nilbacardit26** [ajostergaard/django-payments-redsys#1]
Hi there!
This is just a question regarding the repo and how to be used together with django's framework: saleor
I would like to know how to integrate it given that:
https://docs.getsaleor.com/en/latest/guides/payments.html#adding-payments
I am writing this because maybe you have done it before or know how to approach the problem. How can I implement all the methods that saleor requires taking into account what you have done so far? I can not come up with the way to implement it. Any hint will be appreciated X)

**Comment by ajostergaard** [comment]
Hi ya - unfortunately this repo does not integrate with Saleor - it integrates with django-payments which Saleor used to use. The link you provided is for Saleor's brand new payment integration method. I have yet to have a good look at that... :( I am also no longer using Redsys so... :-/

**Comment by nilbacardit26** [comment]
Thank you! I appreciate your answer :)
